version: '3.8'
services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5579199o
      POSTGRES_DB: tg_bot
    ports:
      - "5432:5432"